FROM puckel/docker-airflow:latest

ARG AIRFLOW_USER_HOME=/usr/local/airflow

ENV PYTHONPATH=$PYTHONPATH:${AIRFLOW_USER_HOME}


# Python packages required for the Selenium Plugin and project specific
USER root

RUN pip install --upgrade pip && \
    pip install docker && \
    pip install selenium && \
    pip install botocore && \
    pip install boto3 && \
    pip install bs4 && \
    pip install lxml && \
    pip install xlrd && \
    pip install flask_bcrypt
    # pip install dbt-core dbt-postgres && \
    # pip install airflow-dbt
    # pip install markupsafe==2.0.1

RUN groupadd --gid 999 docker \
    && usermod -aG docker airflow 

USER airflow 

RUN chown -R airflow ${AIRFLOW_USER_HOME}

RUN mkdir downloads
RUN mkdir outputs
COPY config/airflow.cfg ${AIRFLOW_USER_HOME}/airflow.cfg